apiVersion: v1
kind: Secret

metadata:
  name: backend-secret
  namespace: enterprise-devops

type: Opaque

stringData:
  DB_PASSWORD: StrongPassword123!
  JWT_SECRET: ChangeThisToAVeryStrongSecretKey123!
