apiVersion: v1
kind: Secret

metadata:
  name: postgres-secret
  namespace: enterprise-devops

type: Opaque

stringData:
  POSTGRES_DB: task_management
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: StrongPassword123!
